import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {buildLogoutUrl,clearProductSession,parseCallbackHash} from './auth.js';

type Observation={title:string;detail:string;at:string;severity:string};
type Passport={status:string;statusLabel:string;assetName:string;guaranteeRef:string;decisionBasis:string;lastCheckedAt:string;checks:number;sources:number;changes:number;reviewsRequired:number;observations:Observation[]};
type Config={hostedUiUrl:string;clientId:string};
type AuthState='loading'|'signed_out'|'authenticated'|'rejected'|'error';
const api='/api';
function safeStoredToken(){try{return window.localStorage.getItem('id_token')??''}catch{return ''}}
function captureCallbackToken(){const idToken=parseCallbackHash(window.location.hash);if(idToken){try{window.localStorage.setItem('id_token',idToken)}catch{} window.history.replaceState({},document.title,window.location.pathname+window.location.search);return idToken}return safeStoredToken()}

function App(){
  const [passport,setPassport]=useState<Passport|null>(null); const [config,setConfig]=useState<Config|null>(null); const [authState,setAuthState]=useState<AuthState>('loading'); const [authDetail,setAuthDetail]=useState(''); const [question,setQuestion]=useState('Essa garantia continua válida para a decisão original?'); const [answer,setAnswer]=useState('');
  useEffect(()=>{let cancelled=false; const run=async()=>{try{const cfg=await fetch(`${api}/config`).then(r=>{if(!r.ok)throw new Error(`config_${r.status}`);return r.json() as Promise<Config>});if(cancelled)return;setConfig(cfg);const bearer=captureCallbackToken();if(!bearer){setAuthState('signed_out');setAuthDetail('No product session was found in this browser.');return}const response=await fetch(`${api}/passport/gp-001`,{headers:{Authorization:`Bearer ${bearer}`}});if(response.status===401){setAuthState('rejected');setAuthDetail('Cognito session found, but the protected product API rejected it.');return}if(!response.ok){setAuthState('error');setAuthDetail(`Passport API returned ${response.status}.`);return}const loaded=await response.json() as Passport;if(cancelled)return;setPassport(loaded);setAuthState('authenticated');setAuthDetail('Authenticated product session established.')}catch(error){if(cancelled)return;setAuthState('error');setAuthDetail(error instanceof Error?error.message:'Unable to load the product session.')}};void run();return()=>{cancelled=true}},[]);
  const redirectUri=()=>window.location.origin+'/';
  const login=()=>{if(!config)return;window.location.href=`${config.hostedUiUrl}/oauth2/authorize?response_type=token&client_id=${encodeURIComponent(config.clientId)}&redirect_uri=${encodeURIComponent(redirectUri())}&scope=openid+email+profile`};
  const signOut=()=>{clearProductSession();if(config)window.location.href=buildLogoutUrl(config.hostedUiUrl,config.clientId,redirectUri());else window.location.reload()};
  const ask=async()=>{const bearer=safeStoredToken();if(!bearer){setAuthState('signed_out');setAuthDetail('Your product session is no longer available.');return}const response=await fetch(`${api}/passport/gp-001/chat`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${bearer}`},body:JSON.stringify({message:question})});if(response.status===401){setAuthState('rejected');setAuthDetail('The protected chat request was rejected by Cognito authorization.');return}const result=await response.json();setAnswer(result.answer??'No governed answer was returned.');if(passport)setPassport({...passport,checks:passport.checks+1})};
  if(authState==='loading')return <main className="shell"><div className="loading">Loading your Guarantee Passport…</div></main>;
  if(authState!=='authenticated'||!passport)return <main className="shell"><div className="card auth-card"><h1>Guarantee Passport</h1><p>{authState==='rejected'?'Your Cognito session was found, but the protected product API rejected it. Sign in again to establish a fresh session.':authState==='error'?'The product could not load its authenticated passport. This is not being presented as an empty passport.':'Sign in is required to open this passport.'}</p>{authDetail&&<small className="auth-detail">{authDetail}</small>}<button onClick={login}>Sign in with Cognito</button></div></main>;
  return <main className="shell"><header><div><div className="eyebrow">ACIDHUB KOS · GUARANTEE PASSPORT</div><h1>{passport.assetName}</h1><p className="muted">{passport.guaranteeRef} · {passport.decisionBasis}</p></div><div className="user">Authenticated<br/><span>Tenant-isolated</span><button className="signout" onClick={signOut}>Sign out</button></div></header><section className="hero"><div><div className="status review"><span></span>{passport.statusLabel}</div><h2>Can this guarantee still support the original decision?</h2><p className="lead">One material change has been observed. The impact is not established yet, so a human review is required before relying on it.</p></div><div className="hero-note"><strong>Last checked</strong><br/>{new Date(passport.lastCheckedAt).toLocaleDateString('en-GB')}<br/><span>No autonomous approval</span></div></section><section className="grid"><div className="card chat"><div className="card-title">Ask about this guarantee <span>Governed explanation</span></div><div className="bubble user-bubble">{question}</div>{answer&&<div className="bubble assistant-bubble">{answer}</div>}<div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)}/><button onClick={ask}>Ask</button></div></div><div className="card"><div className="card-title">Current picture <span>Operational view</span></div><div className="metrics"><div><b>{passport.checks}</b><small>checks</small></div><div><b>{passport.sources}</b><small>sources</small></div><div><b className="red">{passport.changes}</b><small>changes</small></div><div><b className="red">{passport.reviewsRequired}</b><small>reviews</small></div></div><div className="freshness"><span>Evidence freshness</span><div className="bar"><i></i></div><small>Current product record · 2 sources</small></div></div></section><section className="grid lower"><div className="card"><div className="card-title">What changed? <span>Timeline</span></div><div className="timeline">{passport.observations.map(o=><div className="event" key={o.title}><i className={o.severity}></i><div><strong>{o.title}</strong><small>{new Date(o.at).toLocaleDateString('en-GB')}</small><p>{o.detail}</p></div></div>)}</div></div><div className="card review-card"><div className="card-title">What still needs review? <span>Human decision</span></div><p>The new condition may affect the collateral basis, but no material impact has been established by this product.</p><div className="review-row"><span>Who needs to decide?</span><b>Credit / risk reviewer</b></div><div className="review-row"><span>Final state</span><b>Review required</b></div><button className="outline">Open review record</button></div></section><footer>Product operational history · Evidence and Foundry integrations are read-only and unavailable in this environment · Studio pattern reused, no Studio mutation</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
